

raw_data_specs:
  ds_name: 'EEG_EC'
  num_nodes: 31
  T_obs: 40000
  num_train: 36855
  num_val: 2000
  num_test: 1000
  context_length: 30
  target_length: 0
  stride: 1
  sample_freq: 5
  nodes: ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'PZ', 'PO3', 'PO7', 'PO4', 'PO8', 'POZ', 'O1', 'O2', 'OZ', 'IZ', 'M1', 'M2', 'TP7', 'TP8', 'CP1', 'CP2', 'CP3', 'CP4', 'CP5', 'CP6', 'CPZ']

data_params:
  num_nodes: 31
  num_subjects: 22
  context_length: 30
  graph_type: 'numeric'
  include_diag: True
  val_size: 1000
  test_size: 500

network_params:
  model_type: 'MultiSubVAE'
  loss_type: 'NLL'
  encoder_hidden_dim: 128
  decoder_hidden_dim: 192
  decoder_tf_interval: 1
  decoder_fix_trajvar: 0.1
  do_prob: 0.1
  MC_samples: 10
  encoder_weight: 0.50
  unit_variance: True
  min_var: 0.01
  max_var: 100
  decoder_style: 'GCNode'

train_params:
  batch_size: 32
  shuffle: True
  max_epochs: 25
  es_patience: null
  warmup_epochs: null
  limit_val_batches: 0.5
  gradient_clip_val: 1
  run_seed: 606

optimizer:
  learning_rate: 0.002
  scheduler_type: 'StepLR'
  step_size: 5
  gamma: 0.25
  interval: 'epoch'
