
data_params:
  num_nodes: 20
  num_subjects: 10
  context_length: 50
  graph_type: 'numeric'
  include_diag: True
  val_size: 1000
  test_size: 500
  graph_key: 'GC'

network_params:
  model_type: 'simOneSubVAE'
  loss_type: 'NLL'
  encoder_hidden_dim: 128
  decoder_hidden_dim: 192
  decoder_tf_interval: 1
  decoder_fix_trajvar: 0.001
  do_prob: 0.1
  unit_variance: True
  min_var: 0.01
  max_var: 100
  decoder_style: 'GCNode'

train_params:
  batch_size: 16
  shuffle: True
  max_epochs: 25
  es_patience: null
  warmup_epochs: null
  limit_val_batches: 0.5
  gradient_clip_val: 1
  run_seed: 606

optimizer:
  learning_rate: 0.0005
  scheduler_type: 'StepLR'
  step_size: 5
  gamma: 0.5
  interval: 'epoch'
